# connect mode : api (direct http[s])
#                slack (via slack)
run_mode: 'api'
api:
  access_url: 'http://localhost:8080/self_iccards/t'
  cert: '1234567890test'
slack:
  token: "xoxb-00000000000-XXXXXXXXXXXXXXXXXXXXXXXX" # Your API token
  channel: '#databus_dev'
  machinename: 'rp1'